spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # auth模块
        - id: cloud-auth
          uri: lb://cloud-auth
          predicates:
            - Path=/auth/**
          filters:
            # 前端密码解密
            - PasswordDecoderFilter
        #demo模块
        - id: cloud-demo
          uri: lb://cloud-demo
          predicates:
            - Path=/demo/**
          filters:
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        #test模块
        - id: cloud-test
          uri: lb://cloud-test
          predicates:
            - Path=/test/**
          filters:
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'